### ISSUE TITLE
Unexpected application root path behaviour

### ISSUE THREAD

**Issue by remonvv** [bbilger/jrestless#21]
Currently the following combination :
- API Gateway resource path = "/api/{+proxy}"
- JAX-RS Resource class @Path("/helloworld")

Does not resolve/work. It is expecting the root resource classes to have the same path prefix as the AG resource path (so @Path("/api/..") in this example). This is unexpected. The combination above should result in :

https://mysite.com/{stage}/api/helloworld

Since the configuration implies the jersey application route is served by the {+proxy} section. It would be good if the Application instance root path is configurable (e.g. through @ApplicationPath which does not seem to be respected) or if the default is changed.

**Comment by bbilger** [comment]
Hi @remonvv ,
You can already configure the baseUri:
```java
public class YourRequestHandler extends GatewayRequestObjectHandler {
  public YourRequestHandler() {
    super(URI.create("/api/")); // use a trailing slash!
    ...
    init(config);
    start();
  }
}
```

Supporting @ApplicationPath might be an idea for the future but I never saw it being supported by any container except servlet containers; I will re-check.

I am not sure if I understand what you mean by "or if the default is changed". One can have multiple API Gateway resource paths e.g. "/api**1**/{+proxy}" , "/api**2**/{+proxy}", ... or even "/api**3**/some/thing" which all invoke the same handler/function, so it's difficult to assume the baseUri automatically.

**Comment by bbilger** [comment]
Hi @remonvv 

>  So in your example I'd expect "api1/api2/api3" to be separate functions/containers defined in serverless.yml

No that's not the case. See for example: https://github.com/bbilger/jrestless-examples/blob/master/aws/gateway/aws-gateway-security-cognito-authorizer/serverless.yml In the example 4 APIGW endpoints are defined: `api/public`, `api/private`, `ui`, `ui/{proxy+}` and all of them use the same function/container. So there really is no way to "assume" the base URI, here. 

Well, you can define the base URI for a resource (class), so you don't have to repeat it on all endpoints (method). See for example https://github.com/bbilger/jrestless-examples/blob/master/aws/gateway/aws-gateway-security-cognito-authorizer/src/main/java/com/jrestless/aws/examples/ApiResource.java

If you are sure about your base URI, I suggest you set it in the handler as suggested above: `super(URI.create("/api/"));` So you no longer have to mention "api" on the resource or endpoint.

I can't think of any other solutions, here, that I could implement in the framework as a general solution since the function (handler, container, resources, endpoints) don't have any clue about APIGW endpoints defined in `serverless.yml`

**Comment by bbilger** [comment]
@remonvv
> If you are sure about your base URI, I suggest you set it in the handler as suggested above: super(URI.create("/api/")); So you no longer have to mention "api" on the resource or endpoint.

Scratch this! This is not doing what it is supposed to do. I think there's a bug; I'll check. (the other points are still valid, though)

**Comment by bbilger** [comment]
What do you think about the following?
```java
package com.jrestless.core.filter;

import java.io.IOException;
import java.net.URI;

import javax.inject.Inject;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.container.PreMatching;
import javax.ws.rs.core.Application;

@PreMatching
public class ApplicationPathFilter implements ContainerRequestFilter {
  private final String applicationPath;
  @Inject
  ApplicationPathFilter(Application applicationConfig) {
    ApplicationPath ap = applicationConfig.getClass().getAnnotation(ApplicationPath.class);
    if (ap != null) {
      String path = ap.value();
      path = path.trim();
      if (!path.startsWith("/")) {
        path = "/" + path;
      }
      if (!path.endsWith("/")) {
        path += "/";
      }
      applicationPath = path;
    } else {
      applicationPath = null;
    }
  }
  @Override
  public void filter(ContainerRequestContext requestContext) throws IOException {
    if (applicationPath != null) {
      URI newUri = URI.create(applicationPath).relativize(requestContext.getUriInfo().getRequestUri());
      newUri = URI.create("/").resolve(newUri);
      requestContext.setRequestUri(newUri);
    }
  }
}
```

You would create a resource config as follows for APIGW:

```java
@ApplicationPath("api")
public class YourConfig extends ResourceConfig {
  public YourConfig() {
    register(ApplicationPathFilter.class);
    register(GatewayFeature.class);
    ...
  }
}
public class RequestHandler extends GatewayRequestObjectHandler {
	public RequestHandler() {
		ResourceConfig config = new YourConfig();
		init(config);
		start();
	}
}
```

**Comment by remonvv** [comment]
@bbilger That's seems like a viable solution to implement my requirement but I think the core design issue remains unaddressed. I think we're having a disconnect about the core problem I'm having. I am short on time now but I'll respond with my thoughts on this today.

**Comment by bbilger** [comment]
Hi @remonvv 
I think I understand now that you don't want to repeat yourself. So what do you think about the following?

Some background:
GatewayRequest#getResource returns what is configured in APIGW e.g. `/api/{proxy+}`. The requestUri will be e.g. `/api/auth`. This filter will set the requestUri to `/auth` and should hopefully fulfill your needs. Note: I didn't test it extensively.

```java
import java.io.IOException;
import java.net.URI;

import javax.annotation.Priority;
import javax.inject.Inject;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.container.PreMatching;

import com.jrestless.aws.gateway.io.GatewayRequest;

@PreMatching
@Priority(0)
public class DynamicApplicationPathFilter implements ContainerRequestFilter {

  private static final String PROXY_SUFFIX = "/{proxy+}";
  private static final URI ROOT_URI = URI.create("/");

  private final GatewayRequest gatwayRequest; // this is a proxy and is
                        // request-scoped

  @Inject
  DynamicApplicationPathFilter(GatewayRequest gatwayRequest) {
    this.gatwayRequest = gatwayRequest;
  }

  @Override
  public void filter(ContainerRequestContext requestContext) throws IOException {
    if (isProxyResourceWithApplicationPath()) {
      URI requestUri = requestContext.getUriInfo().getRequestUri();
      URI newUri = getDynamicApplicationPath().relativize(requestUri);
      newUri = ROOT_URI.resolve(newUri);
      requestContext.setRequestUri(newUri);
    }
  }

  private boolean isProxyResourceWithApplicationPath() {
    String resource = gatwayRequest.getResource();
    if (resource == null) {
      return false;
    } else if (PROXY_SUFFIX.equals(resource)) {
      return false;
    }
    return resource.endsWith(PROXY_SUFFIX);
  }

  private URI getDynamicApplicationPath() {
    String resource = gatwayRequest.getResource();
    return URI.create(resource.substring(0, resource.length() - PROXY_SUFFIX.length()));
  }
}
``` 

Let me know if this works for you.

I can add this to the framework if you need it but I don't want to enable it by default since in my opinion there are too many cases where this behavior is not accurate/desired. You would be able to enable it by registering it in your ResourceConfig.

**Comment by remonvv** [comment]
Hi @bbilger 

Do you have Skype or some way of real-time coms? I think there's either a misunderstanding or a bug. For example, if I checkout and deploy the usage-example project it does not work (the endpoint isn're reachable at {stage}/health/sample) which I suspect is a side effect of the issue/concern I'm talking about ( serverless.yml - http: ANY / does not seem to result in a reachable endpoint regardless of Jersey/@Path config)

**Comment by bbilger** [comment]
Hi @remonvv,
You can reach me via skype (bjoern.bilger) after 20:00 CET (this week Tuesday and Wednesday, only)

**Comment by bbilger** [comment]
created https://github.com/bbilger/jrestless/issues/24 and https://github.com/bbilger/jrestless/issues/23 to introduce the filters discussed, here (DynamicApplicationPathFilter, ApplicationPathFilter)
closing this ticket

**Comment by bbilger** [comment]
Hi @remonvv ,
it's been a while (have been quite busy; sorry) but in case you are still interested, JRestless should support what you need, now: DynamicProxyBasePathFilter which must be registered explicitly. 
I updated the way JRestless handles the base- and request URI in v0.5.0 and it's described here: https://github.com/bbilger/jrestless/blob/master/docs/src/docs/asciidoc/uri_handling.adoc
