### ISSUE TITLE
jrestless incompatible with jersey 2.26

### ISSUE THREAD

**Issue by boardthatpowder** [bbilger/jrestless#41]
Jrestless is not compatible with Jersey 2.26 due to removing `ServiceLocator` and replacing `InjectionManager`:

http://javaarm.com/file/glassfish/jersey/doc/userguide/Jersey-2.26-User-Guide.htm#mig-2.26-injection-manager

**Comment by bbilger** [comment]
Oh, thanks for pointing this out.
I'll take a look as soon as possible. Since I am pretty busy right now, it'll take some time, unfortunately.

**Comment by bbilger** [comment]
I updated to Jersey 2.26 on master.
It will, however, take some more time before this can be released since I need to update the examples in [bbilger/jrestless-examples](https://github.com/bbilger/jrestless-examples) and run regressions.

**Comment by bbilger** [comment]
The fix is out with JRestless 0.6.0 which was released last weekend.

Sorry it took me a little longer but I got fooled by the new alternative injection manager: `jersey-cdi2-se`. 
I thought there were some issues in JRestless but it turns out it's actually an issue in `jersey-cdi2-se ` that affects other containers (e.g. Grizzly), as well: https://github.com/jersey/jersey/issues/3621. (I overlooked that Jersey's release notes mention that `jersey-cdi2-se` is not yet ready for production.)

Note that CDI is still working using `jersey-hk2` together with `jersey-weld2-se`: https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-cdi
