### ISSUE TITLE
Progress on dropwizard applications with jrestless on aws lambda?

### ISSUE THREAD

**Issue by kennovak-zy** [bbilger/jrestless#46]
I saw comments on issues #27 and #34 with @injeniero and @vikrampatankar regarding running dropwizard.  I think @injeniero may have a working example, and I see a [repo was created but never filled](https://github.com/injeniero/dropwizard-jrestless).  

Has jrestless ever been used for dropwizard? If so, any hints on how to do that?

Many thanks

**Comment by bbilger** [comment]
Hi @kennovak-zy ,
No news regarding this unfortunately. I really hoped @injeniero would share how he managed to make JRestless work with dropwizard.
So I can just repeat what has been said here: https://github.com/awslabs/aws-serverless-java-container/issues/128#issuecomment-369317745
It should be possible somehow... but I don't know for sure since I don't use dropwizard.
